version: '3'

services:
  cadmiumcrocodile:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  glasssun:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  onyxlion:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
