apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: glass-sun
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: glass-sun
    spec:
      containers:
      - name: glass-sun
        image: ethos.azurecr.io/glasssun:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: onyx-lion
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: onyx-lion
    spec:
      containers:
      - name: onyx-lion
        image: ethos.azurecr.io/onyxlion:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cadmium-crocodile
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cadmium-crocodile
    spec:
      containers:
      - name: cadmium-crocodile
        image: ethos.azurecr.io/cadmiumcrocodile:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 80